apiVersion: v1
kind: Namespace
metadata:
  name: ingress-gateway
  labels:
    app.kubernetes.io/part-of: trust-graph
---
apiVersion: v1
kind: Namespace
metadata:
  name: workloads
  labels:
    app.kubernetes.io/part-of: trust-graph
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    app.kubernetes.io/part-of: trust-graph
---
apiVersion: v1
kind: Namespace
metadata:
  name: egress-gateway
  labels:
    app.kubernetes.io/part-of: trust-graph
